/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ShellAdminRouteImport } from './routes/_shell/admin'
import { Route as ShellBuildItineraryRouteImport } from './routes/_shell/build-itinerary'
import { Route as ShellCalendarRouteImport } from './routes/_shell/calendar'
import { Route as ShellCommunityRouteImport } from './routes/_shell/community'
import { Route as ShellCreateTripRouteImport } from './routes/_shell/create-trip'
import { Route as ShellDashboardRouteImport } from './routes/_shell/dashboard'
import { Route as ShellDiscoverRouteImport } from './routes/_shell/discover'
import { Route as ShellItineraryViewRouteImport } from './routes/_shell/itinerary-view'
import { Route as ShellLandingRouteImport } from './routes/_shell/landing'
import { Route as ShellProfileRouteImport } from './routes/_shell/profile'
import { Route as ShellSearchRouteImport } from './routes/_shell/search'
import { Route as ShellTripsRouteImport } from './routes/_shell/trips'
import { Route as ShellTripsIndexRouteImport } from './routes/_shell/trips/index'
import { Route as ShellTripsTripIdRouteImport } from './routes/_shell/trips/$tripId'
import { Route as ShellTripsTripIdIndexRouteImport } from './routes/_shell/trips/$tripId/index'
import { Route as ShellTripsTripIdBudgetRouteImport } from './routes/_shell/trips/$tripId/budget'
import { Route as ShellTripsTripIdCalendarRouteImport } from './routes/_shell/trips/$tripId/calendar'
import { Route as ShellTripsTripIdItineraryRouteImport } from './routes/_shell/trips/$tripId/itinerary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAdminRoute = ShellAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBuildItineraryRoute = ShellBuildItineraryRouteImport.update({
  id: '/build-itinerary',
  path: '/build-itinerary',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCalendarRoute = ShellCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCommunityRoute = ShellCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCreateTripRoute = ShellCreateTripRouteImport.update({
  id: '/create-trip',
  path: '/create-trip',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDiscoverRoute = ShellDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => ShellRoute,
} as any)
const ShellItineraryViewRoute = ShellItineraryViewRouteImport.update({
  id: '/itinerary-view',
  path: '/itinerary-view',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLandingRoute = ShellLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSearchRoute = ShellSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTripsRoute = ShellTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTripsIndexRoute = ShellTripsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellTripsRoute,
} as any)
const ShellTripsTripIdRoute = ShellTripsTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => ShellTripsRoute,
} as any)
const ShellTripsTripIdIndexRoute = ShellTripsTripIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellTripsTripIdRoute,
} as any)
const ShellTripsTripIdBudgetRoute = ShellTripsTripIdBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => ShellTripsTripIdRoute,
} as any)
const ShellTripsTripIdCalendarRoute =
  ShellTripsTripIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => ShellTripsTripIdRoute,
  } as any)
const ShellTripsTripIdItineraryRoute =
  ShellTripsTripIdItineraryRouteImport.update({
    id: '/itinerary',
    path: '/itinerary',
    getParentRoute: () => ShellTripsTripIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof ShellAdminRoute
  '/build-itinerary': typeof ShellBuildItineraryRoute
  '/calendar': typeof ShellCalendarRoute
  '/community': typeof ShellCommunityRoute
  '/create-trip': typeof ShellCreateTripRoute
  '/dashboard': typeof ShellDashboardRoute
  '/discover': typeof ShellDiscoverRoute
  '/itinerary-view': typeof ShellItineraryViewRoute
  '/landing': typeof ShellLandingRoute
  '/profile': typeof ShellProfileRoute
  '/search': typeof ShellSearchRoute
  '/trips': typeof ShellTripsRouteWithChildren
  '/trips/$tripId': typeof ShellTripsTripIdRouteWithChildren
  '/trips/': typeof ShellTripsIndexRoute
  '/trips/$tripId/budget': typeof ShellTripsTripIdBudgetRoute
  '/trips/$tripId/calendar': typeof ShellTripsTripIdCalendarRoute
  '/trips/$tripId/itinerary': typeof ShellTripsTripIdItineraryRoute
  '/trips/$tripId/': typeof ShellTripsTripIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin': typeof ShellAdminRoute
  '/build-itinerary': typeof ShellBuildItineraryRoute
  '/calendar': typeof ShellCalendarRoute
  '/community': typeof ShellCommunityRoute
  '/create-trip': typeof ShellCreateTripRoute
  '/dashboard': typeof ShellDashboardRoute
  '/discover': typeof ShellDiscoverRoute
  '/itinerary-view': typeof ShellItineraryViewRoute
  '/landing': typeof ShellLandingRoute
  '/profile': typeof ShellProfileRoute
  '/search': typeof ShellSearchRoute
  '/trips': typeof ShellTripsIndexRoute
  '/trips/$tripId/budget': typeof ShellTripsTripIdBudgetRoute
  '/trips/$tripId/calendar': typeof ShellTripsTripIdCalendarRoute
  '/trips/$tripId/itinerary': typeof ShellTripsTripIdItineraryRoute
  '/trips/$tripId': typeof ShellTripsTripIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_shell/admin': typeof ShellAdminRoute
  '/_shell/build-itinerary': typeof ShellBuildItineraryRoute
  '/_shell/calendar': typeof ShellCalendarRoute
  '/_shell/community': typeof ShellCommunityRoute
  '/_shell/create-trip': typeof ShellCreateTripRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/discover': typeof ShellDiscoverRoute
  '/_shell/itinerary-view': typeof ShellItineraryViewRoute
  '/_shell/landing': typeof ShellLandingRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/search': typeof ShellSearchRoute
  '/_shell/trips': typeof ShellTripsRouteWithChildren
  '/_shell/trips/$tripId': typeof ShellTripsTripIdRouteWithChildren
  '/_shell/trips/': typeof ShellTripsIndexRoute
  '/_shell/trips/$tripId/budget': typeof ShellTripsTripIdBudgetRoute
  '/_shell/trips/$tripId/calendar': typeof ShellTripsTripIdCalendarRoute
  '/_shell/trips/$tripId/itinerary': typeof ShellTripsTripIdItineraryRoute
  '/_shell/trips/$tripId/': typeof ShellTripsTripIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/build-itinerary'
    | '/calendar'
    | '/community'
    | '/create-trip'
    | '/dashboard'
    | '/discover'
    | '/itinerary-view'
    | '/landing'
    | '/profile'
    | '/search'
    | '/trips'
    | '/trips/$tripId'
    | '/trips/'
    | '/trips/$tripId/budget'
    | '/trips/$tripId/calendar'
    | '/trips/$tripId/itinerary'
    | '/trips/$tripId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/build-itinerary'
    | '/calendar'
    | '/community'
    | '/create-trip'
    | '/dashboard'
    | '/discover'
    | '/itinerary-view'
    | '/landing'
    | '/profile'
    | '/search'
    | '/trips'
    | '/trips/$tripId/budget'
    | '/trips/$tripId/calendar'
    | '/trips/$tripId/itinerary'
    | '/trips/$tripId'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/register'
    | '/_shell/admin'
    | '/_shell/build-itinerary'
    | '/_shell/calendar'
    | '/_shell/community'
    | '/_shell/create-trip'
    | '/_shell/dashboard'
    | '/_shell/discover'
    | '/_shell/itinerary-view'
    | '/_shell/landing'
    | '/_shell/profile'
    | '/_shell/search'
    | '/_shell/trips'
    | '/_shell/trips/$tripId'
    | '/_shell/trips/'
    | '/_shell/trips/$tripId/budget'
    | '/_shell/trips/$tripId/calendar'
    | '/_shell/trips/$tripId/itinerary'
    | '/_shell/trips/$tripId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/admin': {
      id: '/_shell/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ShellAdminRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/build-itinerary': {
      id: '/_shell/build-itinerary'
      path: '/build-itinerary'
      fullPath: '/build-itinerary'
      preLoaderRoute: typeof ShellBuildItineraryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/calendar': {
      id: '/_shell/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof ShellCalendarRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/community': {
      id: '/_shell/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof ShellCommunityRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/create-trip': {
      id: '/_shell/create-trip'
      path: '/create-trip'
      fullPath: '/create-trip'
      preLoaderRoute: typeof ShellCreateTripRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/discover': {
      id: '/_shell/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof ShellDiscoverRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/itinerary-view': {
      id: '/_shell/itinerary-view'
      path: '/itinerary-view'
      fullPath: '/itinerary-view'
      preLoaderRoute: typeof ShellItineraryViewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/landing': {
      id: '/_shell/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof ShellLandingRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/search': {
      id: '/_shell/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ShellSearchRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/trips': {
      id: '/_shell/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof ShellTripsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/trips/': {
      id: '/_shell/trips/'
      path: '/'
      fullPath: '/trips/'
      preLoaderRoute: typeof ShellTripsIndexRouteImport
      parentRoute: typeof ShellTripsRoute
    }
    '/_shell/trips/$tripId': {
      id: '/_shell/trips/$tripId'
      path: '/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof ShellTripsTripIdRouteImport
      parentRoute: typeof ShellTripsRoute
    }
    '/_shell/trips/$tripId/': {
      id: '/_shell/trips/$tripId/'
      path: '/'
      fullPath: '/trips/$tripId/'
      preLoaderRoute: typeof ShellTripsTripIdIndexRouteImport
      parentRoute: typeof ShellTripsTripIdRoute
    }
    '/_shell/trips/$tripId/budget': {
      id: '/_shell/trips/$tripId/budget'
      path: '/budget'
      fullPath: '/trips/$tripId/budget'
      preLoaderRoute: typeof ShellTripsTripIdBudgetRouteImport
      parentRoute: typeof ShellTripsTripIdRoute
    }
    '/_shell/trips/$tripId/calendar': {
      id: '/_shell/trips/$tripId/calendar'
      path: '/calendar'
      fullPath: '/trips/$tripId/calendar'
      preLoaderRoute: typeof ShellTripsTripIdCalendarRouteImport
      parentRoute: typeof ShellTripsTripIdRoute
    }
    '/_shell/trips/$tripId/itinerary': {
      id: '/_shell/trips/$tripId/itinerary'
      path: '/itinerary'
      fullPath: '/trips/$tripId/itinerary'
      preLoaderRoute: typeof ShellTripsTripIdItineraryRouteImport
      parentRoute: typeof ShellTripsTripIdRoute
    }
  }
}

interface ShellTripsTripIdRouteChildren {
  ShellTripsTripIdBudgetRoute: typeof ShellTripsTripIdBudgetRoute
  ShellTripsTripIdCalendarRoute: typeof ShellTripsTripIdCalendarRoute
  ShellTripsTripIdItineraryRoute: typeof ShellTripsTripIdItineraryRoute
  ShellTripsTripIdIndexRoute: typeof ShellTripsTripIdIndexRoute
}

const ShellTripsTripIdRouteChildren: ShellTripsTripIdRouteChildren = {
  ShellTripsTripIdBudgetRoute: ShellTripsTripIdBudgetRoute,
  ShellTripsTripIdCalendarRoute: ShellTripsTripIdCalendarRoute,
  ShellTripsTripIdItineraryRoute: ShellTripsTripIdItineraryRoute,
  ShellTripsTripIdIndexRoute: ShellTripsTripIdIndexRoute,
}

const ShellTripsTripIdRouteWithChildren =
  ShellTripsTripIdRoute._addFileChildren(ShellTripsTripIdRouteChildren)

interface ShellTripsRouteChildren {
  ShellTripsTripIdRoute: typeof ShellTripsTripIdRouteWithChildren
  ShellTripsIndexRoute: typeof ShellTripsIndexRoute
}

const ShellTripsRouteChildren: ShellTripsRouteChildren = {
  ShellTripsTripIdRoute: ShellTripsTripIdRouteWithChildren,
  ShellTripsIndexRoute: ShellTripsIndexRoute,
}

const ShellTripsRouteWithChildren = ShellTripsRoute._addFileChildren(
  ShellTripsRouteChildren,
)

interface ShellRouteChildren {
  ShellAdminRoute: typeof ShellAdminRoute
  ShellBuildItineraryRoute: typeof ShellBuildItineraryRoute
  ShellCalendarRoute: typeof ShellCalendarRoute
  ShellCommunityRoute: typeof ShellCommunityRoute
  ShellCreateTripRoute: typeof ShellCreateTripRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDiscoverRoute: typeof ShellDiscoverRoute
  ShellItineraryViewRoute: typeof ShellItineraryViewRoute
  ShellLandingRoute: typeof ShellLandingRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellSearchRoute: typeof ShellSearchRoute
  ShellTripsRoute: typeof ShellTripsRouteWithChildren
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAdminRoute: ShellAdminRoute,
  ShellBuildItineraryRoute: ShellBuildItineraryRoute,
  ShellCalendarRoute: ShellCalendarRoute,
  ShellCommunityRoute: ShellCommunityRoute,
  ShellCreateTripRoute: ShellCreateTripRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDiscoverRoute: ShellDiscoverRoute,
  ShellItineraryViewRoute: ShellItineraryViewRoute,
  ShellLandingRoute: ShellLandingRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellSearchRoute: ShellSearchRoute,
  ShellTripsRoute: ShellTripsRouteWithChildren,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
